[package]
name = "leptos-qr"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "QR Code Component for Leptos"

[package.metadata.docs.rs]
targets = [ "wasm32-unknown-unknown" ]

[dependencies]
fast_qr = { version = "0.12.5", features = [ "svg", "wasm-bindgen" ] }
leptos = "0.6.15"
