[package]
name = "csr"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
console_error_panic_hook = "0.1"
leptos = { version = "0.6", features = ["csr"] }
leptos-qr = { path = "../.." }
